format:
 :csv_splitor: ';'
 :update_marker: 'DOUPDATE'
 :file_max_size: 20971520
 
path:
 :updata_file_path: 'uploadfiles/data'
 :download_file_path: 'uploadfiles/download'
 :template_file_path: 'uploadfiles/template'
 :import_delivery_file_path: 'uploadfiles/delivery'
 :import_users_file_path: 'uploadfiles/users'
 :import_parts_file_path: 'uploadfiles/parts'
 :import_part_positions_file_path: 'uploadfiles/part_positions'
 :import_fors_report_file_path: 'uploadfiles/fors_reports'

api:
 auth:
  user: 'UPDATE'
  passwd: 'S12@#4DSA'

log:
 :log_folder: 'tmp/log'