# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f7aec891176615141a320db59240125ebab7c421fd1caa3b548c33be5dc36949d89a250d63f90e5ee804dec4a62264e6098d76691f83345089d6775a350911

test:
  secret_key_base: 0b8af7b2b4c70523a7136e4de576ac9cc11c1f69a800ecc4a047b316279b2b47e3d5275fd1af395ce60b95c04333d86e829069b8ffc05f2d4f8dbd38cac6e706

server:
  secret_key_base: 0b8af7b2b4c70523a7136e4de576ac9cc11c1f69a800ecc4a047b316279b2b47e3d5275fd1af395ce60b95c04333d86e829069b8ffc05f2d4f8dbd38cac6e706

sync1:
  secret_key_base: 0b8af7b2b4c70523a7136e4de576ac9cc11c1f69a800ecc4a047b316279b2b47e3d5275fd1af395ce60b95c04333d86e829069b8ffc05f2d4f8dbd38cac6e706

sync2:
  secret_key_base: 0b8af7b2b4c70523a7136e4de576ac9cc11c1f69a800ecc4a047b316279b2b47e3d5275fd1af395ce60b95c04333d86e829069b8ffc05f2d4f8dbd38cac6e706

development_test:
  secret_key_base: 94f7aec891176615141a320db59240125ebab7c421fd1caa3b548c33be5dc36949d89a250d63f90e5ee804dec4a62264e6098d76691f83345089d6775a350911

leoni:
  secret_key_base: 888c87c7705f500b5827d46440e5972f86938212632938a90919f46d5208e002edae577d59f005ce9c05b92b5bc938df37ad8a4250ad80358f4613c39d6c0549
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
