---
sync:
  host: http://192.168.0.109:9000
  token: 3dcba17f596969a676bfdd90b5425c703f983acf7306760e1057c95afe9f17b1d
  sync_lock: false
  enabled: false
  advance_second: 1800
  per_request_size: 0
  lock: false
  executor:
    location:
      name: "地点"
      get: true
      post: true
      put: true
      delete: true
    location_destination:
      name: "目的地"
      get: true
      post: true
      put: true
      delete: true
    hacker:
      name: "员工"
      get: false
      post: false
      put: false
      delete: false
    whouse:
      name: "仓库"
      get: false
      post: false
      put: false
      delete: false
    part_type:
      name: "零件类型"
      get: false
      post: false
      put: false
      delete: false
    part:
      name: "零件"
      get: false
      post: false
      put: false
      delete: false
    position:
      name: "库位"
      get: false
      post: false
      put: false
      delete: false
    part_position:
      name: "零件库位"
      get: false
      post: false
      put: false
      delete: false
    regex_category:
      name: "正则类别"
      get: false
      post: false
      put: false
      delete: false
    regex:
      name: "正则项"
      get: false
      post: false
      put: false
      delete: false
    container:
      name: "容器"
      get: true
      post: true
      put: true
      delete: true
    location_container:
      name: "容器层次"
      get: true
      post: true
      put: true
      delete: true
    record:
      name: "操作记录"
      get: true
      post: true
      put: true
      delete: true
    storage:
      name: "库存"
      get: false
      post: false
      put: false
      delete: false
    pick_item_filter:
      name: "员工择货规则"
      get: false
      post: false
      put: false
      delete: false
    order:
      name: "需求单"
      get: false
      post: false
      put: false
      delete: false
    order_item:
      name: "需求单项目"
      get: false
      post: false
      put: false
      delete: false
    pick_list:
      name: "择货单"
      get: false
      post: false
      put: false
      delete: false
    pick_item:
      name: "择货单项"
      get: false
      post: false
      put: false
      delete: false
